name: BDD Full Tests

on:
  pull_request:
    branches: ['**']

permissions:
  contents: read

jobs:
  full-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run BDD Full Tests
        run: npm run test:full
